# Testing configuration for worker-router.js (Phase 2 refactoring)
# Usage: wrangler dev --config wrangler.router.toml

name = "manuscript-upload-api-router"
main = "worker-router.js"  # NEW ENTRY POINT
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

# Serve frontend files as static assets
[assets]
directory = "./frontend"
binding = "ASSETS"

# Enable logging
logpush = false
observability = { enabled = true }

# Queue for async analysis
[[queues.producers]]
queue = "manuscript-analysis-queue"
binding = "ANALYSIS_QUEUE"

# Queue consumer for processing analysis jobs
[[queues.consumers]]
queue = "manuscript-analysis-queue"
max_batch_size = 1
max_batch_timeout = 60
max_retries = 3
dead_letter_queue = "manuscript-analysis-dlq"

# Queue for async asset generation
[[queues.producers]]
queue = "asset-generation-queue"
binding = "ASSET_QUEUE"

# Queue consumer for processing asset generation jobs
[[queues.consumers]]
queue = "asset-generation-queue"
max_batch_size = 1
max_batch_timeout = 60
max_retries = 2
dead_letter_queue = "asset-generation-dlq"

# R2 Bucket bindings
[[r2_buckets]]
binding = "MANUSCRIPTS_RAW"
bucket_name = "manuscripts-raw"

[[r2_buckets]]
binding = "MANUSCRIPTS_PROCESSED"
bucket_name = "manuscripts-processed"

[[r2_buckets]]
binding = "MARKETING_ASSETS"
bucket_name = "marketing-assets"

[[r2_buckets]]
binding = "BACKUPS"
bucket_name = "manuscript-platform-backups"

# Scheduled CRON trigger for automated backups
[triggers]
crons = ["0 3 * * *"]

# D1 Database
[[d1_databases]]
binding = "DB"
database_name = "manuscript-platform"
database_id = "3d9000ef-95fb-4561-bb84-192b395eadd2"

# KV Namespace
[[kv_namespaces]]
binding = "SESSIONS"
id = "48959d60fe25478db01651f3eef4daff"

# Environment variables
[vars]
MAX_FILE_SIZE = 52428800
SESSION_DURATION = 1800
STRIPE_PUBLISHABLE_KEY = "pk_live_51SMYSaGlyuXwBKzmxt41kzNWsyJWvVoTh6Ik2fMpRMVVT8oZC8VMqv0Yldu1SIuCvRxDzEGRJBA2gTCdZgiKnYp400wCyfuh6Q"
FRONTEND_URL = "https://scarter4workmanuscripthub.com"
EMAIL_FROM_ADDRESS = "noreply@scarter4workmanuscripthub.com"
EMAIL_FROM_NAME = "ManuscriptHub"
EMAIL_ADMIN_ADDRESS = "scarter4work@yahoo.com"
EMAIL_REPLY_TO_ADDRESS = "support@scarter4workmanuscripthub.com"
