name = "manuscript-upload-api"
main = "worker.js"
compatibility_date = "2024-01-01"

# Enable logging
logpush = false
observability = { enabled = true }

# R2 Bucket bindings
[[r2_buckets]]
binding = "MANUSCRIPTS_RAW"
bucket_name = "manuscripts-raw"

[[r2_buckets]]
binding = "MANUSCRIPTS_PROCESSED"
bucket_name = "manuscripts-processed"

[[r2_buckets]]
binding = "MARKETING_ASSETS"
bucket_name = "marketing-assets"

# Note: Custom domain is configured via Cloudflare Dashboard
# Go to Workers & Pages > manuscript-upload-api > Custom Domains
# Add: api.scarter4workmanuscripthub.com