name = "manuscript-analysis-consumer"
main = "analysis-queue-consumer.js"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

# Enable logging
logpush = false
observability = { enabled = true }

# Queue consumer configuration
[[queues.consumers]]
queue = "manuscript-analysis-queue"
max_batch_size = 1
max_batch_timeout = 30
max_retries = 3
dead_letter_queue = "manuscript-analysis-dlq"

# R2 Bucket bindings (same as main worker)
[[r2_buckets]]
binding = "MANUSCRIPTS_RAW"
bucket_name = "manuscripts-raw"

[[r2_buckets]]
binding = "MANUSCRIPTS_PROCESSED"
bucket_name = "manuscripts-processed"

# Environment variables
[vars]
# ANTHROPIC_API_KEY will be set via dashboard secrets for production
